# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias l='ls -CF'

alias vim="vim -X"
alias tmux="tmux -2"
alias g="git"

# Git stuff
alias g="git"
alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias ga="git add"
alias gaa="git add --all"
alias gps="git push"
alias gpl="git pull"
alias gr="git rebase"
alias gl="git log"
alias gh="git hist"
# Git Flow
alias gfi="git flow init"
alias gff="git flow feature"
alias gfr="git flow release"
alias gfh="git flow hotfix"

if [ -f /etc/bash_completion.d/git ]; then
  source /etc/bash_completion.d/git
fi
__git_complete g _git

function gc {
  git commit -m "$(IFS=, ; echo "$@")"
}

alias test-phantom="karma start --no-single-run --auto-watch --browsers PhantomJS --reporters dots"
alias test-chrome="karma start --no-single-run --auto-watch --browsers Chrome --reporters dots"

alias vim=nvim
alias vi=nvim

alias tmate="tmate -f ~/.tmate.conf"

function rspec-watch {
  FILES=$1
  echo "$FILES" | entr -c bundle exec rspec "$FILES"
}

