# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias l='ls -CF'

alias vim="vim -X"
alias tmux="tmux -2"
alias g="git"

. ~/.git_aliases

function gc {
  git commit -m "$(IFS=, ; echo "$@")"
}

alias test-phantom="karma start --no-single-run --auto-watch --browsers PhantomJS --reporters dots"
alias test-chrome="karma start --no-single-run --auto-watch --browsers Chrome --reporters dots"

alias vim=nvim
alias vi=nvim

alias tmate="tmate -f ~/.tmate.conf"

function rspec-watch {
  FILES=$1
  find . -name '*.rb' | entr -c bundle exec rspec "$FILES"
}

function jq-color {
  jq --color-output $@ | less -R
}

function haddock-open {
  for pkg in "$@"; do
    firefox "$(ghc-pkg field "$pkg" haddock-html | tr -d ':' | cut -d ' ' -f 2 | sed -e 's/$/\/index.html/g')"
  done
}


alias nix-shell-add-gc-root='file shell.nix && mkdir .nix-gc-roots && nix-instantiate shell.nix --indirect --add-root .nix-gc-roots/shell.drv'
