source /usr/share/bash-completion/completions/git

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Load in the git branch prompt script.
source ~/.git-prompt.sh
export TERM=screen-256color
export EDITOR=nvim

PS1='\[\033[0;31m\]\w\[\033[0;32m\]$(__git_ps1)\[\e[0m\]$ '

export NVM_DIR="/home/owi/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.dotfiles/bin

# added by travis gem
[ -f /home/owi/.travis/travis.sh ] && source /home/owi/.travis/travis.sh

if [ -f ~/.ghc-pkg-functions.sh ]; then
    . ~/.ghc-pkg-functions.sh
fi

