alias vim="vim -X"
alias tmux="tmux -2"
alias g="git"

# Git stuff
alias g="git"
alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias ga="git add"
alias gaa="git add --all"
alias gps="git push"
alias gpl="git pull"
alias gr="git rebase"
alias gl="git log"
alias gh="git hist"
# Git Flow
alias gfi="git flow init"
alias gff="git flow feature"
alias gfr="git flow release"
alias gfh="git flow hotfix"

__git_complete g _git

function gc {
  git commit -m "$(IFS=, ; echo "$@")"
}

alias test-phantom="karma start --no-single-run --auto-watch --browsers PhantomJS --reporters dots"
alias test-chrome="karma start --no-single-run --auto-watch --browsers Chrome --reporters dots"
