set guioptions-=T  "remove toolbar
set guioptions-=m  "remove menu
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=R  "remove right-hand scroll bar
set guioptions-=l  "remove left-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set guioptions-=e  " use text-mode tab bar

set linespace=1

colorscheme Tomorrow-Night
set background=dark

" STATUS LINE

hi User1 ctermfg=240 guifg=#777777 ctermbg=236 guibg=#333333
hi User2 ctermfg=11 guifg=#FFFF00 ctermbg=236 guibg=#333333
hi User3 ctermfg=245 guifg=#555555 ctermbg=236 guibg=#333333

hi CommandTSelection guibg=#3c3836 guifg=#b8bb26

if has("gui_running")
    if has("gui_gtk2")

        " GVIM UBUNTU
        set guifont=Source\ Code\ Pro\ 12
        vmap <C-c> "+yi
        vmap <C-x> "+c
        vmap <C-v> c<ESC>"+p
        imap <C-v> <C-r><C-o>+

        map <silent> <F11> :call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")<CR>

    elseif has("gui_macvim")

        " MACVIM
        set guifont=Source\ Code\ Pro:h15

    elseif has("gui_win32")

        " GVIM WINDOWS
        set guifont=Consolas:h14:cANSI

    endif
endif
