" PATHOGEN

execute pathogen#infect()

" GENERAL SETUP

set nocompatible            " get rid of Vi compatibility mode. SET FIRST!
filetype plugin indent on   " filetype detection[ON] plugin[ON] indent[ON]
syntax enable               " enable syntax highlighting (previously syntax on).
set t_Co=256
colorscheme Tomorrow-Night

highlight SignColumn ctermbg=none     " no color for gutter
highlight CommandTSelection ctermbg=238 ctermfg=green
highlight Visual ctermbg=238

highlight VertSplit ctermfg=253 ctermbg=245

set colorcolumn=80

" set number                  " show line numbers
set laststatus=22           " last window always has a statusline
filetype indent on          " activates indenting for files
set nohlsearch              " Don't continue to highlight searched phrases.
set hlsearch                " Highlight all results
set incsearch               " But do highlight as you type your search.
set ignorecase              " Make searches case-insensitive.
set ruler                   " Always show info along bottom.

" INDENTATION
set cindent
set autoindent              " auto-indent
set tabstop=2               " tab spacing
set softtabstop=2           " unify
set shiftwidth=2            " indent/outdent by 2 columns
set shiftround              " always indent/outdent to the nearest tabstop
set expandtab               " use spaces instead of tabs
set smarttab                " use tabs at the start of a line, spaces elsewhere

autocmd FileType make setlocal noexpandtab
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4
au BufNewFile,BufRead *.ejs set filetype=html

set nowrap                  " don't wrap text
set cmdheight=1
set ttyfast

let mapleader = ','

" Disable arrow keys
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

" NEOCOMPLCACHE

" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplcache.
let g:neocomplcache_enable_at_startup = 1
" Use smartcase.
let g:neocomplcache_enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplcache_min_syntax_length = 3

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplcache#undo_completion()
inoremap <expr><C-l>     neocomplcache#complete_common_string()

" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplcache#close_popup()
inoremap <expr><C-e>  neocomplcache#cancel_popup()

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Popup color.
"highlight Pmenu ctermbg=grey
"highlight PmenuSel ctermfg=white ctermbg=black
"highlight PmenuSbar ctermbg=0

" HASKELL SETUP

" Use GHC functionality for haskell source files
au Bufenter *.hs compiler ghc
let g:haddock_browser = "/usr/bin/google-chrome"
let g:ghc = "/usr/bin/ghc"


" JAVASCRIPT SETUP

let javascript_enable_domhtmlcss = 1

" Syntax checking
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_enable_signs=1
let g:syntastic_always_populate_loc_list=1


" Command-T

" General ignores
set wildignore+=dist/**,out/**,build/**,_build/**,*.obj,.git
" JS, Bower, Node ignores
set wildignore+=**/bower-components/**,**/bower_components/**,**/node_modules/**

" Auto-flush Command-T when saving file or switching to Vim.
augroup CommandTExtension
  autocmd!
  autocmd FocusGained * CommandTFlush
  autocmd BufWritePost * CommandTFlush
augroup END

" TagBar
nmap <F8> :TagbarToggle<CR>

" Spell Checking Commands
:command EnableSpellCheck :set spell spelllang=en_us
:command DisableSpellCheck :set nospell

" Rainbow Parens
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
"
" Enable custom .vim.custom in directories
if filereadable(".vim.custom")
    so .vim.custom
endif

" DELIMIT MATE
let delimitMate_expand_cr=1

" VIM GO

" Import package under cursor.
au FileType go nmap <Leader>i <Plug>(go-import)

" Open godoc for word under cursor.
au FileType go nmap <Leader>gd <Plug>(go-doc)

" Run command for current file.
au FileType go nmap <leader>gr <Plug>(go-run)
au FileType go nmap <leader>gb <Plug>(go-build)
au FileType go nmap <leader>gt <Plug>(go-test)

" Replace gd with go-def.
au FileType go nmap gd <Plug>(go-def)
" And for opening in splits.
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)

" Markdown syntax
au BufRead,BufNewFile *.md set filetype=markdown
